#!/bin/bash
#
# Sailing Dev Install - Local installation from sailing repo (symlink mode)
#
# Usage: /path/to/sailing/devinstall.sh [options]
#        Run from target project directory
#
# Creates symlinks to the sailing repo - changes reflected immediately.
# For standalone installation, use install.sh instead.
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

FORCE=false
FULL_MODE=false
FOLDERS_PROFILE=""

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --help|-h)
      echo "Sailing Dev Install - Local installation from sailing repo"
      echo
      echo "Usage: /path/to/sailing/devinstall.sh [options]"
      echo "       Run from target project directory"
      echo
      echo "Creates symlinks to the sailing repo."
      echo "Changes to the repo are immediately reflected."
      echo "For standalone installation, use install.sh instead."
      echo
      echo "Options:"
      echo "  --force              Force overwrite existing files"
      echo "  --full               Enable subprocess mode (worktrees, auto-spawn)"
      echo "  --folders-profile=X  Use folder profile: project (default), haven, sibling"
      echo "  --help, -h           Show this help"
      echo
      echo "Examples:"
      echo "  cd /path/to/my-project"
      echo "  /path/to/sailing/devinstall.sh"
      echo "  /path/to/sailing/devinstall.sh --force"
      echo
      exit 0
      ;;
    --force)
      FORCE=true
      shift
      ;;
    --full)
      FULL_MODE=true
      shift
      ;;
    --folders-profile=*)
      FOLDERS_PROFILE="${1#*=}"
      shift
      ;;
    --folders-profile)
      FOLDERS_PROFILE="$2"
      shift 2
      ;;
    *)
      echo -e "${RED}Unknown option: $1${NC}"
      echo "Use --help for usage"
      exit 1
      ;;
  esac
done

# Validate folders profile
if [ -n "$FOLDERS_PROFILE" ]; then
  case "$FOLDERS_PROFILE" in
    project|haven|sibling)
      ;;
    *)
      echo -e "${RED}Invalid folders profile: $FOLDERS_PROFILE${NC}"
      echo "Valid profiles: project, haven, sibling"
      exit 1
      ;;
  esac
fi

echo -e "${BLUE}Sailing Dev Install${NC} (symlink mode)"
echo "===================="
echo

# 1. Resolve script directory (sailing repo)
SCRIPT_DIR="$(dirname "$(realpath "$0")")"

# 2. Verify we're running from a sailing repo
if [ ! -d "$SCRIPT_DIR/cli" ] || [ ! -d "$SCRIPT_DIR/skill" ]; then
  echo -e "${RED}Error: Script must be in a sailing repo (missing cli/ or skill/)${NC}"
  exit 1
fi

# 3. Verify we're NOT in the sailing repo itself
if [ "$(realpath "$(pwd)")" = "$SCRIPT_DIR" ]; then
  echo -e "${RED}Error: Run from target project directory, not from sailing repo${NC}"
  echo "Usage: cd /path/to/your/project && $0"
  exit 1
fi

echo -e "Source repo: ${GREEN}$SCRIPT_DIR${NC}"
echo -e "Target project: ${GREEN}$(pwd)${NC}"
echo

# 4. Default paths
DEFAULT_SAILING_DIR=".sailing"
ARTEFACTS=".sailing/artefacts"
MEMORY=".sailing/memory"
STATE_FILE=".sailing/state.json"
COMPONENTS_FILE=".sailing/components.yaml"
SKILL=".claude/skills/sailing"
COMMANDS=".claude/commands/dev"
# Note: templates and prompting use ^/ prefix in paths.yaml (no local copy)

# Read custom paths from existing paths.yaml (if any)
CONFIG_FILE="${DEFAULT_SAILING_DIR}/paths.yaml"
if [ -f "$CONFIG_FILE" ]; then
  echo -e "${BLUE}Reading paths from existing paths.yaml...${NC}"

  parse_yaml_path() {
    grep -E "^\s*$1:" "$CONFIG_FILE" 2>/dev/null | sed 's/.*:\s*//' | tr -d '"' | tr -d "'" || echo ""
  }

  CUSTOM_ARTEFACTS=$(parse_yaml_path "artefacts")
  CUSTOM_MEMORY=$(parse_yaml_path "memory")
  CUSTOM_STATE=$(parse_yaml_path "state")
  CUSTOM_COMPONENTS=$(parse_yaml_path "components")
  CUSTOM_SKILL=$(parse_yaml_path "skill")
  CUSTOM_COMMANDS=$(parse_yaml_path "commands")

  [ -n "$CUSTOM_ARTEFACTS" ] && ARTEFACTS="$CUSTOM_ARTEFACTS"
  [ -n "$CUSTOM_MEMORY" ] && MEMORY="$CUSTOM_MEMORY"
  [ -n "$CUSTOM_STATE" ] && STATE_FILE="$CUSTOM_STATE"
  [ -n "$CUSTOM_COMPONENTS" ] && COMPONENTS_FILE="$CUSTOM_COMPONENTS"
  [ -n "$CUSTOM_SKILL" ] && SKILL="$CUSTOM_SKILL"
  [ -n "$CUSTOM_COMMANDS" ] && COMMANDS="$CUSTOM_COMMANDS"
fi

# 5. Create necessary directories
echo -e "${BLUE}Creating directories...${NC}"
mkdir -p "$DEFAULT_SAILING_DIR"
mkdir -p "$ARTEFACTS/prds"
mkdir -p "$MEMORY"
mkdir -p "$(dirname "$SKILL")"
mkdir -p "$(dirname "$COMMANDS")"
mkdir -p bin

echo -e "${GREEN}Directories created${NC}"
echo

# 6. Create bin/rudder wrapper
echo -e "${BLUE}Creating bin/rudder...${NC}"

cat > bin/rudder << EOF
#!/bin/bash
# Rudder CLI wrapper - dev mode pointing to sailing repo
# Auto-generated by devinstall.sh
SAILING_PROJECT="\$(realpath "\$(dirname "\$0")/..")" exec node "$SCRIPT_DIR/cli/rudder.js" "\$@"
EOF

chmod +x bin/rudder
echo -e "${GREEN}Created: bin/rudder (→ source repo)${NC}"
echo

# 7. Create symlinks
echo -e "${BLUE}Creating symlinks...${NC}"

create_symlink() {
  local src="$1"
  local dest="$2"

  # Check if destination exists and is not a symlink
  if [ -e "$dest" ] && [ ! -L "$dest" ]; then
    if [ "$FORCE" = "true" ]; then
      rm -rf "$dest"
      echo -e "  ${YELLOW}Removed existing: $dest${NC}"
    else
      echo -e "  ${YELLOW}Skipped (exists): $dest - use --force to overwrite${NC}"
      return
    fi
  fi

  ln -sfn "$src" "$dest"
  echo -e "  ${GREEN}Linked: $dest → $src${NC}"
}

# Skill
create_symlink "$SCRIPT_DIR/skill" "$SKILL"

# Commands
create_symlink "$SCRIPT_DIR/commands/dev" "$COMMANDS"

# Templates: handled via ^/templates in paths.yaml (like prompting)

echo

# 8. Copy protected files if they don't exist (or --force)
echo -e "${BLUE}Checking protected files...${NC}"

copy_protected() {
  local src="$1"
  local dest="$2"

  if [ ! -f "$dest" ] || [ "$FORCE" = true ]; then
    cp "$src" "$dest"
    echo -e "  ${GREEN}Created: $dest${NC}"
  else
    echo -e "  ${YELLOW}Preserved: $dest${NC}"
  fi
}

# paths.yaml always goes in .sailing/ (config.yaml created only if needed)
copy_protected "$SCRIPT_DIR/dist/paths.yaml-dist" "$DEFAULT_SAILING_DIR/paths.yaml"

# These respect paths.yaml configuration
mkdir -p "$(dirname "$COMPONENTS_FILE")"
copy_protected "$SCRIPT_DIR/dist/components.yaml-dist" "$COMPONENTS_FILE"
copy_protected "$SCRIPT_DIR/dist/ROADMAP.md-dist" "$ARTEFACTS/ROADMAP.md"
copy_protected "$SCRIPT_DIR/dist/POSTIT.md-dist" "$ARTEFACTS/POSTIT.md"

# =============================================================================
# LEGACY HANDLING - Remove old core/ directory (replaced by prompting/)
# =============================================================================
if [ -d "$DEFAULT_SAILING_DIR/core" ]; then
  echo -e "${BLUE}Cleaning up legacy files...${NC}"
  rm -rf "$DEFAULT_SAILING_DIR/core"
  echo -e "  ${GREEN}Removed: $DEFAULT_SAILING_DIR/core/ (replaced by prompting/)${NC}"
fi

echo

# 9. Configure repo paths in paths.yaml (must use ^/ prefix for devinstall)
echo -e "${BLUE}Configuring repo paths...${NC}"

configure_repo_path() {
  local key="$1"
  local value="^/$key"

  if ! grep -q "^[[:space:]]*$key:" "$DEFAULT_SAILING_DIR/paths.yaml" 2>/dev/null; then
    echo "  $key: $value" >> "$DEFAULT_SAILING_DIR/paths.yaml"
    echo -e "  ${GREEN}Added: $key: $value${NC}"
  elif ! grep -q "$key:.*\^/$key" "$DEFAULT_SAILING_DIR/paths.yaml" 2>/dev/null; then
    echo -e "  ${YELLOW}Warning: paths.yaml has custom $key path${NC}"
    echo -e "  ${YELLOW}For devinstall, it MUST be: $key: $value${NC}"
  else
    echo -e "  ${GREEN}OK: $key: $value${NC}"
  fi
}

configure_repo_path "prompting"
configure_repo_path "templates"

echo

# 10. npm install in source repo (if needed)
if [ ! -d "$SCRIPT_DIR/node_modules" ]; then
  echo -e "${BLUE}Installing npm dependencies in source repo...${NC}"
  (cd "$SCRIPT_DIR" && npm install --silent 2>/dev/null) || {
    echo -e "${YELLOW}npm install had warnings (this is usually OK)${NC}"
  }
  echo -e "${GREEN}Dependencies installed${NC}"
  echo
fi

# 11. Configure Claude permissions
echo -e "${BLUE}Configuring Claude Code permissions...${NC}"
bin/rudder permissions:fix || {
  echo -e "${YELLOW}Could not configure permissions automatically.${NC}"
  echo "  Run manually: bin/rudder permissions:fix"
}
echo

# 12. Apply folder profile (optional)
if [ -n "$FOLDERS_PROFILE" ]; then
  echo -e "${BLUE}Applying folder profile: $FOLDERS_PROFILE${NC}"

  PATHS_FILE="$DEFAULT_SAILING_DIR/paths.yaml"

  # For devinstall, we always preserve ^/ prefixes for prompting/templates
  # Only configure worktrees/agents paths based on profile

  case "$FOLDERS_PROFILE" in
    project)
      # Append worktree paths if not present
      if ! grep -q "^worktrees:" "$PATHS_FILE" 2>/dev/null; then
        echo 'worktrees: "%haven%/worktrees/%project_hash%"' >> "$PATHS_FILE"
        echo -e "  ${GREEN}Added: worktrees path${NC}"
      fi
      if ! grep -q "^agents:" "$PATHS_FILE" 2>/dev/null; then
        echo 'agents: "%haven%/agents"' >> "$PATHS_FILE"
        echo -e "  ${GREEN}Added: agents path${NC}"
      fi
      ;;
    haven)
      if ! grep -q "^worktrees:" "$PATHS_FILE" 2>/dev/null; then
        echo 'worktrees: "%haven%/worktrees"' >> "$PATHS_FILE"
        echo -e "  ${GREEN}Added: worktrees path${NC}"
      fi
      if ! grep -q "^agents:" "$PATHS_FILE" 2>/dev/null; then
        echo 'agents: "%haven%/agents"' >> "$PATHS_FILE"
        echo -e "  ${GREEN}Added: agents path${NC}"
      fi
      ;;
    sibling)
      if ! grep -q "^worktrees:" "$PATHS_FILE" 2>/dev/null; then
        echo 'worktrees: "%sibling%/worktrees"' >> "$PATHS_FILE"
        echo -e "  ${GREEN}Added: worktrees path${NC}"
      fi
      if ! grep -q "^agents:" "$PATHS_FILE" 2>/dev/null; then
        echo 'agents: "%sibling%/agents"' >> "$PATHS_FILE"
        echo -e "  ${GREEN}Added: agents path${NC}"
      fi
      ;;
  esac
  echo
fi

# 13. Apply full mode (optional)
if [ "$FULL_MODE" = true ]; then
  echo -e "${BLUE}Enabling full mode (subprocess + worktrees)${NC}"

  CONFIG_FILE="$DEFAULT_SAILING_DIR/config.yaml"

  # Create or update config.yaml
  if [ ! -f "$CONFIG_FILE" ]; then
    cat > "$CONFIG_FILE" << 'EOF'
# Sailing configuration
agent:
  # Enable subprocess mode (Claude spawned as subprocess)
  use_subprocess: true
  # Enable worktree isolation for parallel agents
  use_worktrees: true
  # Skip permission prompts (requires use_subprocess)
  risky_mode: true
  # Enable sandbox mode (requires use_subprocess)
  sandbox: true
  timeout: 3600
  merge_strategy: merge
EOF
    echo -e "  ${GREEN}Created: $CONFIG_FILE with subprocess+worktree mode enabled${NC}"
  else
    # Update or add use_subprocess
    if grep -q "use_subprocess:" "$CONFIG_FILE" 2>/dev/null; then
      sed -i 's/use_subprocess:.*/use_subprocess: true/' "$CONFIG_FILE"
    else
      if grep -q "^agent:" "$CONFIG_FILE" 2>/dev/null; then
        sed -i '/^agent:/a\  use_subprocess: true' "$CONFIG_FILE"
      else
        echo -e "\nagent:\n  use_subprocess: true" >> "$CONFIG_FILE"
      fi
    fi
    echo -e "  ${GREEN}Set: use_subprocess: true${NC}"

    # Update or add use_worktrees
    if grep -q "use_worktrees:" "$CONFIG_FILE" 2>/dev/null; then
      sed -i 's/use_worktrees:.*/use_worktrees: true/' "$CONFIG_FILE"
    else
      if grep -q "^agent:" "$CONFIG_FILE" 2>/dev/null; then
        sed -i '/^agent:/a\  use_worktrees: true' "$CONFIG_FILE"
      else
        echo -e "\nagent:\n  use_worktrees: true" >> "$CONFIG_FILE"
      fi
    fi
    echo -e "  ${GREEN}Set: use_worktrees: true${NC}"
  fi
  echo
fi

# Done
echo -e "${GREEN}Dev install complete!${NC}"
echo
echo "Usage:"
echo "  bin/rudder --help"
echo
echo "Changes to $SCRIPT_DIR will be immediately reflected."
echo
