#!/bin/bash
#
# Sailing Dev Install - Local installation from sailing repo
#
# Usage: /path/to/sailing/devinstall.sh [options]
#        Run from target project directory
#
# Modes:
#   --symlink  (default) Create symlinks to repo - changes reflected immediately
#   --copy     Copy files like install.sh - standalone installation
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Defaults
MODE="symlink"
FORCE=false

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --help|-h)
      echo "Sailing Dev Install - Local installation from sailing repo"
      echo
      echo "Usage: /path/to/sailing/devinstall.sh [options]"
      echo "       Run from target project directory"
      echo
      echo "Modes:"
      echo "  --symlink    Create symlinks to repo (default)"
      echo "               Changes to sailing repo are immediately reflected"
      echo "               CLI runs from source repo"
      echo
      echo "  --copy       Copy files like install.sh"
      echo "               Standalone installation, no dependency on source repo"
      echo "               CLI copied to .sailing/rudder/"
      echo
      echo "Options:"
      echo "  --force      Force overwrite existing files (skill, commands, protected files)"
      echo "  --help, -h   Show this help"
      echo
      echo "Examples:"
      echo "  cd /path/to/my-project"
      echo "  /path/to/sailing/devinstall.sh              # symlink mode"
      echo "  /path/to/sailing/devinstall.sh --copy       # copy mode"
      echo
      exit 0
      ;;
    --symlink)
      MODE="symlink"
      shift
      ;;
    --copy)
      MODE="copy"
      shift
      ;;
    --force)
      FORCE=true
      shift
      ;;
    *)
      echo -e "${RED}Unknown option: $1${NC}"
      echo "Use --help for usage"
      exit 1
      ;;
  esac
done

echo -e "${BLUE}Sailing Dev Install${NC} (mode: $MODE)"
echo "===================="
echo

# 1. Resolve script directory (sailing repo)
SCRIPT_DIR="$(dirname "$(realpath "$0")")"

# 2. Verify we're running from a sailing repo
if [ ! -d "$SCRIPT_DIR/cli" ] || [ ! -d "$SCRIPT_DIR/skill" ]; then
  echo -e "${RED}Error: Script must be in a sailing repo (missing cli/ or skill/)${NC}"
  exit 1
fi

# 3. Verify we're NOT in the sailing repo itself
if [ "$(realpath "$(pwd)")" = "$SCRIPT_DIR" ]; then
  echo -e "${RED}Error: Run from target project directory, not from sailing repo${NC}"
  echo "Usage: cd /path/to/your/project && $0"
  exit 1
fi

echo -e "Source repo: ${GREEN}$SCRIPT_DIR${NC}"
echo -e "Target project: ${GREEN}$(pwd)${NC}"
echo

# 4. Create necessary directories
echo -e "${BLUE}Creating directories...${NC}"
mkdir -p .sailing/{artefacts/prds,memory,core}
mkdir -p .claude/{skills,commands}
mkdir -p bin

if [ "$MODE" = "copy" ]; then
  mkdir -p .sailing/rudder
fi

echo -e "${GREEN}Directories created${NC}"
echo

# 5. Create bin/rudder wrapper
echo -e "${BLUE}Creating bin/rudder...${NC}"

if [ "$MODE" = "symlink" ]; then
  cat > bin/rudder << EOF
#!/bin/bash
# Rudder CLI wrapper - dev mode pointing to sailing repo
# Auto-generated by devinstall.sh --symlink
SAILING_PROJECT="\$(realpath "\$(dirname "\$0")/..")" exec node "$SCRIPT_DIR/cli/rudder.js" "\$@"
EOF
  echo -e "${GREEN}Created: bin/rudder (→ source repo)${NC}"
else
  cat > bin/rudder << 'EOF'
#!/bin/bash
# Rudder CLI wrapper - points to .sailing/rudder/
# Auto-generated by devinstall.sh --copy
SCRIPT_DIR="$(dirname "$(realpath "$0")")"
exec node "$SCRIPT_DIR/../.sailing/rudder/cli/rudder.js" "$@"
EOF
  echo -e "${GREEN}Created: bin/rudder (→ .sailing/rudder/)${NC}"
fi

chmod +x bin/rudder
echo

# 6. Install skill, commands, templates, core docs
echo -e "${BLUE}Installing files ($MODE mode)...${NC}"

install_item() {
  local src="$1"
  local dest="$2"
  local is_dir="$3"
  local force_overwrite="$4"

  # Check if destination exists and is not a symlink
  if [ -e "$dest" ] && [ ! -L "$dest" ]; then
    if [ "$force_overwrite" = "true" ] || [ "$FORCE" = "true" ]; then
      rm -rf "$dest"
      echo -e "  ${YELLOW}Removed existing: $dest${NC}"
    else
      echo -e "  ${YELLOW}Skipped (exists): $dest - use --force to overwrite${NC}"
      return
    fi
  fi

  if [ "$MODE" = "symlink" ]; then
    ln -sfn "$src" "$dest"
    echo -e "  ${GREEN}Linked: $dest${NC}"
  else
    if [ "$is_dir" = "true" ]; then
      rm -rf "$dest"
      cp -r "$src" "$dest"
    else
      cp "$src" "$dest"
    fi
    echo -e "  ${GREEN}Copied: $dest${NC}"
  fi
}

# Skill (always overwrite with --force)
install_item "$SCRIPT_DIR/skill" ".claude/skills/sailing" true true

# Commands (always overwrite with --force)
install_item "$SCRIPT_DIR/commands/dev" ".claude/commands/dev" true true

# Templates
install_item "$SCRIPT_DIR/templates" ".sailing/templates" true

# Core docs (reference documentation)
for f in SAILING.md RUDDER.md VERSIONING.md MILESTONE.md TASKLOG.md; do
  if [ -f "$SCRIPT_DIR/core/$f" ]; then
    install_item "$SCRIPT_DIR/core/$f" ".sailing/core/$f" false
  fi
done

# CLI (copy mode only)
if [ "$MODE" = "copy" ]; then
  echo -e "${BLUE}Installing Rudder CLI...${NC}"
  cp -r "$SCRIPT_DIR/cli"/* .sailing/rudder/
  cp "$SCRIPT_DIR/package.json" .sailing/rudder/
  echo -e "  ${GREEN}Copied: .sailing/rudder/${NC}"
fi

echo

# 7. Copy protected files if they don't exist (or --force)
echo -e "${BLUE}Checking protected files...${NC}"

copy_protected() {
  local src="$1"
  local dest="$2"

  if [ ! -f "$dest" ] || [ "$FORCE" = true ]; then
    cp "$src" "$dest"
    echo -e "  ${GREEN}Created: $dest${NC}"
  else
    echo -e "  ${YELLOW}Preserved: $dest${NC}"
  fi
}

copy_protected "$SCRIPT_DIR/dist/paths.yaml-dist" ".sailing/paths.yaml"
copy_protected "$SCRIPT_DIR/dist/components.yaml-dist" ".sailing/components.yaml"
copy_protected "$SCRIPT_DIR/dist/ROADMAP.md-dist" ".sailing/artefacts/ROADMAP.md"
copy_protected "$SCRIPT_DIR/dist/POSTIT.md-dist" ".sailing/artefacts/POSTIT.md"

echo

# 8. Ensure core: ^/core in paths.yaml (devinstall mode)
echo -e "${BLUE}Configuring devinstall paths...${NC}"
if ! grep -q "^[[:space:]]*core:" ".sailing/paths.yaml" 2>/dev/null; then
  # No core entry - add it
  echo "" >> ".sailing/paths.yaml"
  echo "  # Core docs from sailing repo (devinstall mode)" >> ".sailing/paths.yaml"
  echo "  core: ^/core" >> ".sailing/paths.yaml"
  echo -e "  ${GREEN}Added: core: ^/core${NC}"
elif ! grep -q "core:.*\^/core" ".sailing/paths.yaml" 2>/dev/null; then
  # core entry exists but not ^/core - warn user
  echo -e "  ${YELLOW}Note: paths.yaml has custom core path (not ^/core)${NC}"
  echo -e "  ${YELLOW}For devinstall, consider: core: ^/core${NC}"
else
  echo -e "  ${GREEN}OK: core: ^/core already configured${NC}"
fi

echo

# 9. npm install
if [ "$MODE" = "symlink" ]; then
  if [ ! -d "$SCRIPT_DIR/node_modules" ]; then
    echo -e "${BLUE}Installing npm dependencies in source repo...${NC}"
    (cd "$SCRIPT_DIR" && npm install --silent 2>/dev/null) || {
      echo -e "${YELLOW}npm install had warnings (this is usually OK)${NC}"
    }
    echo -e "${GREEN}Dependencies installed${NC}"
    echo
  fi
else
  echo -e "${BLUE}Installing npm dependencies...${NC}"
  (cd .sailing/rudder && npm install --silent 2>/dev/null) || {
    echo -e "${YELLOW}npm install had warnings (this is usually OK)${NC}"
  }
  echo -e "${GREEN}Dependencies installed${NC}"
  echo
fi

# 10. Configure Claude permissions
echo -e "${BLUE}Configuring Claude Code permissions...${NC}"
bin/rudder permissions:fix || {
  echo -e "${YELLOW}Could not configure permissions automatically.${NC}"
  echo "  Run manually: bin/rudder permissions:fix"
}
echo

# Done
echo -e "${GREEN}Dev install complete!${NC}"
echo
echo "Usage:"
echo "  bin/rudder --help"
echo

if [ "$MODE" = "symlink" ]; then
  echo "Changes to $SCRIPT_DIR will be immediately reflected."
else
  echo "Standalone installation - no dependency on source repo."
fi
echo
