#!/bin/bash
# Mock Claude Code for E2E testing
# Simulates a successful agent run without consuming any API tokens.
#
# Behavior:
# - Reads prompt from stdin (discards it)
# - Parses --mcp-config to locate agent directory
# - Creates a dummy file in CWD (the worktree)
# - Writes a valid result.yaml in the agent directory
# - Outputs stream-json events on stdout
# - Exits 0

AGENT_DIR=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --mcp-config) AGENT_DIR=$(dirname "$2"); shift 2 ;;
    -p) shift ;;  # stdin prompt flag
    *) shift ;;
  esac
done

# Consume stdin prompt
cat > /dev/null

# Create a dummy file change in CWD (worktree or project root)
echo "// Generated by mock-claude" > mock-output.txt
git add mock-output.txt 2>/dev/null
git commit -m "feat: mock agent work" --no-verify 2>/dev/null

# Write result.yaml in agent dir (if found)
if [[ -n "$AGENT_DIR" && -d "$AGENT_DIR" ]]; then
  NOW=$(date -u +"%Y-%m-%dT%H:%M:%S.000Z")
  cat > "$AGENT_DIR/result.yaml" << RESULT
---
version: "1"
task_id: "${MOCK_TASK_ID:-T001}"
status: completed

files_modified:
  - path: mock-output.txt
    action: created

log:
  - level: info
    message: "Mock agent started"
    timestamp: "$NOW"
  - level: info
    message: "Mock agent completed"
    timestamp: "$NOW"

issues: []
completed_at: "$NOW"
---

Mock agent completed successfully.
RESULT
fi

# Output stream-json to stdout
echo '{"type":"system","subtype":"init","model":"mock-claude-1.0","tools":[]}'
sleep 0.1
echo '{"type":"assistant","message":{"content":[{"type":"text","text":"Mock agent completed successfully."}]}}'
sleep 0.1
echo '{"type":"result","subtype":"success","num_turns":1,"total_cost_usd":0.00}'

exit 0
